config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get 'homes/mypage'
  resources :users, only: [:index, :show, :edit, :update]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  get 'homes/about' => 'homes#about', as: 'about'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :user_rooms
  has_many :chats
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    # チャットするユーザーのIDを取得
    @user = User.find(params[:id])
    # ログイン中のユーザーの中間テーブルであるuser_roomsを介して、ログイン中のユーザーのIDと一致するroom_idの値を配列でroomsに代入
    rooms = current_user.user_rooms.pluck(:room_id)
    # チャットするユーザーとログイン中のユーザーですでにroomが存在するかチェック。あれば取得。なければ空。
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    # user_roomが空でないならtrue,空ならfalse
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      # use_roomが空の場合(チャットしたことなかった人の場合)、新しくroomを作成する
      @room = Room.new
      @room.save
      # 中間テーブルにログイン中のユーザーのIDとroomのIDを作成、保存
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      # 中間テーブルにチャットするユーザーのIDとroomのIDを作成、保存
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    # room内でのチャットを取得して、インスタンス変数に代入
    @chats = @room.chats
    # 新しくチャットできるようにチャットの新規作成。引数にroom_idには部屋のIDを
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def mypage
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.post_image_id = post_image.id
    comment.save
redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
  private
  def post_comment_params
    params.require(:post_comment).permit(:comment, :user_id, :post_image_id)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
  end

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<%= form_with model:@chat , url: chats_path, method: :post do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
  <%= f.submit %>
<% end %>
<table>
  <thead>
    <tr>
      <td>投稿者名</td>
      <td>投稿内容</td>
    </tr>
  </thead>
  <tbody>
    <% @chats.each do |chat| %>
      <td><%= chat.user.name %></td>
      <td><%= chat.message %></td>
    <% end %>
  </tbody>
</table>

app/views/post_images/index.html.erb
<h1>投稿一覧</h1>
<% @post_images.each do |post_image| %>
  <div>
    <%= link_to post_image_path(post_image.id)  do %>
      <%= image_tag post_image.get_image %>
    <% end %>
    <p>投稿ユーザー画像:<%= image_tag post_image.user.get_profile_image(100,100) %></p>
    <p>ショップ名:<% post_image.shop_name %></p>
    <p>説明:<%= post_image.caption %></p>
    <p>ユーザーネーム:<%= post_image.user.name %></p>
    <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
  </div>
<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: 'image/*' %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>

  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<h1>投稿詳細</h1>
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名:<%= @post_image.shop_name %></p>
  <p>説明:<%= @post_image.caption %></p>
  <p>投稿ユーザー画像:<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム<%= @post_image.user.name %></p>
  <p>投稿日:<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
  <%= link_to "削除する", post_image_path(@post_image.id) %>
  <% end %>
</div>
<div>
  <p>コメント件数:<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image.id, post_comment.id), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment %>
    <%= f.submit '送信する' %>
  <% end %>
</div>